// SPDX-License-Identifier: GPL-3.0-or-later
import 'dart:convert';
import 'dart:io';
import 'dart:ui';

import 'package:archive/archive.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../../../../core/logging.dart';
import '../../../../utils/share_utils.dart';
import '../models/diagnostic_run.dart';
import '../models/diagnostic_summary.dart';
import 'diagnostic_capture_service.dart';

/// Handles building the diagnostic export bundle (zip).
class DiagnosticExportService {
  /// Build and export a diagnostic zip bundle.
  ///
  /// Returns the path to the created zip file.
  static Future<String> buildZip({
    required DiagnosticRun run,
    required DiagnosticSummary summary,
    required DiagnosticCaptureService capture,
  }) async {
    final archive = Archive();

    // 1. environment.json
    final envJson = run.toEnvironmentJson();
    archive.addFile(
      ArchiveFile(
        'environment.json',
        utf8.encode(envJson).length,
        utf8.encode(envJson),
      ),
    );

    // 2. summary.json
    final summaryJson = summary.toJsonString();
    archive.addFile(
      ArchiveFile(
        'summary.json',
        utf8.encode(summaryJson).length,
        utf8.encode(summaryJson),
      ),
    );

    // 3. packets.ndjson
    final ndjson = capture.toNdjson();
    archive.addFile(
      ArchiveFile(
        'packets.ndjson',
        utf8.encode(ndjson).length,
        utf8.encode(ndjson),
      ),
    );

    // 4. logs.txt
    final logs = capture.toFilteredLog();
    archive.addFile(
      ArchiveFile('logs.txt', utf8.encode(logs).length, utf8.encode(logs)),
    );

    // 5. README.txt
    const readme = '''Socialmesh Admin Diagnostic Bundle
===================================

This bundle was generated by the Socialmesh Admin Diagnostic Harness.

Contents:
  environment.json  - Device, app, transport, and target metadata
  summary.json      - Per-probe pass/fail results and suspected causes
  packets.ndjson    - Full packet capture (one JSON object per line)
  logs.txt          - Filtered diagnostic log lines

How to use:
  - Open summary.json for a quick overview of failures
  - Use packets.ndjson for detailed packet-level debugging
  - Share this zip with support or paste summary.json into an LLM

Format: NDJSON lines are newline-delimited JSON (one object per line).
        base64 payloads in payloadB64 fields are raw protobuf bytes.
''';
    archive.addFile(
      ArchiveFile(
        'README.txt',
        utf8.encode(readme).length,
        utf8.encode(readme),
      ),
    );

    // Encode to zip
    final zipData = ZipEncoder().encode(archive);

    // Write to temp directory
    final tempDir = await getTemporaryDirectory();
    final fileName = 'socialmesh_diagnostic_${run.runId}.zip';
    final filePath = '${tempDir.path}/$fileName';
    final file = File(filePath);
    await file.writeAsBytes(zipData);

    AppLogging.adminDiag('Diagnostic bundle saved: $filePath');
    return filePath;
  }

  /// Share the diagnostic zip via the platform share sheet.
  static Future<void> share({
    required String zipPath,
    required String runId,
    Rect? sharePosition,
  }) async {
    await shareFiles(
      [XFile(zipPath)],
      subject: 'Socialmesh Diagnostic $runId',
      text: 'Admin diagnostic bundle from Socialmesh',
      sharePositionOrigin: sharePosition,
    );
  }
}
