// SPDX-License-Identifier: GPL-3.0-or-later
import 'dart:convert';
import 'dart:io';
import 'dart:ui';

import 'package:archive/archive.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../../../core/logging.dart';
import 'conformance_runner.dart';

/// Builds and exports the conformance run zip bundle.
///
/// Bundle contents:
///   - summary.json          — per-test pass/fail, latency, anomalies
///   - environment.json      — run metadata
///   - packets.ndjson        — full packet capture
///   - provider_state.ndjson — provider state snapshots at each step
///   - logs.txt              — filtered diagnostic log lines
class ConformanceExporter {
  /// Build and share the conformance export bundle.
  ///
  /// Returns the path to the created zip file.
  static Future<String> export(ConformanceRunResult result) async {
    final archive = Archive();
    final summary = result.summary;
    final capture = result.capture;
    final ctx = result.context;

    // 1. summary.json
    _addFile(archive, 'summary.json', summary.toJsonString());

    // 2. environment.json
    final envJson = const JsonEncoder.withIndent('  ').convert({
      'runId': summary.runId,
      'startedAt': summary.startedAt.toIso8601String(),
      'finishedAt': summary.finishedAt.toIso8601String(),
      'suiteType': summary.suiteType.name,
      'target': {
        'isLocal': ctx.isLocal,
        'nodeNum': ctx.targetNodeNum,
        'myNodeNum': ctx.myNodeNum,
      },
      'destructiveMode': ctx.destructiveMode,
    });
    _addFile(archive, 'environment.json', envJson);

    // 3. packets.ndjson
    _addFile(archive, 'packets.ndjson', capture.toNdjson());

    // 4. provider_state.ndjson
    _addFile(archive, 'provider_state.ndjson', ctx.stateSnapshotsToNdjson());

    // 5. logs.txt
    _addFile(archive, 'logs.txt', capture.toFilteredLog());

    // 6. README.txt
    _addFile(archive, 'README.txt', _readme);

    // Encode to zip
    final zipData = ZipEncoder().encode(archive);

    // Write to temp directory
    final tempDir = await getTemporaryDirectory();
    final fileName = 'socialmesh_conformance_${summary.runId}.zip';
    final filePath = '${tempDir.path}/$fileName';
    final file = File(filePath);
    await file.writeAsBytes(zipData);

    AppLogging.adminDiag('Conformance bundle written to $filePath');
    return filePath;
  }

  /// Build and share the conformance bundle via the system share sheet.
  static Future<void> share(
    ConformanceRunResult result, {
    Rect? sharePositionOrigin,
  }) async {
    final filePath = await export(result);
    final xFile = XFile(filePath);

    await SharePlus.instance.share(
      ShareParams(
        files: [xFile],
        title: 'Socialmesh Conformance Bundle',
        sharePositionOrigin: sharePositionOrigin,
      ),
    );
  }

  static void _addFile(Archive archive, String name, String content) {
    final bytes = utf8.encode(content);
    archive.addFile(ArchiveFile(name, bytes.length, bytes));
  }

  static const _readme = '''Socialmesh Device Conformance Bundle
=====================================

This bundle was generated by the Socialmesh Device Conformance Harness.

Contents:
  summary.json          - Per-test pass/fail with latency stats and anomalies
  environment.json      - Run metadata (target, mode, timing)
  packets.ndjson        - Full packet capture (one JSON object per line)
  provider_state.ndjson - Provider state snapshots at each conformance step
  logs.txt              - Filtered diagnostic log lines

How to interpret:
  - summary.json: Check 'results' array for per-domain pass/fail.
    'suspectedAnomalies' highlights data-driven patterns.
    'latencyByDomain' shows timing statistics.
  - provider_state.ndjson: Each line is a state snapshot with phase
    (before_load, after_load, before_save, after_save, after_readback).
    Compare states across phases to detect hydration or cache bleed.
  - packets.ndjson: TX/RX packet pairs correlated by packet ID.

Format: NDJSON = newline-delimited JSON (one object per line).
''';
}
