// SPDX-License-Identifier: GPL-3.0-or-later
// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw_mJqrlJNTAjQDLIknLphzEcmGdAN-wg',
    appId: '1:571509151050:android:db85cbb852c9098a515db3',
    messagingSenderId: '571509151050',
    projectId: 'social-mesh-app',
    storageBucket: 'social-mesh-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8M3-03k2ETTMRKADHFTcw7w0nnZNSEj4',
    appId: '1:571509151050:ios:34008143a4671f9c515db3',
    messagingSenderId: '571509151050',
    projectId: 'social-mesh-app',
    storageBucket: 'social-mesh-app.firebasestorage.app',
    iosClientId:
        '571509151050-7fa2c8p7b88ibpkd3hcpgr85v5kl7cjf.apps.googleusercontent.com',
    iosBundleId: 'com.gotnull.socialmesh',
  );
}
