#!/usr/bin/env python3
"""Report translation coverage for each locale ARB file.

Compares every locale file against the English template (app_en.arb) and
reports:
  - Missing keys (not present in the locale file at all)
  - Untranslated keys (present but identical to English)
  - Translated keys (present and different from English)

Outputs a summary to stdout and writes a detailed TRANSLATION_STATUS.md
to the project root.

Exit codes:
  0 — always (this is a reporting tool, not a gate)
"""

import json
import re
import sys
import time
from collections import defaultdict
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
L10N_DIR = PROJECT / "lib" / "l10n"
TEMPLATE = "app_en.arb"
STATUS_FILE = PROJECT / "TRANSLATION_STATUS.md"


def load_arb(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def get_translation_keys(data: dict) -> list[str]:
    return sorted(k for k in data if not k.startswith("@") and k != "@@locale")


def key_prefix(key: str) -> str:
    m = re.match(r"^[a-z]+", key)
    return m.group() if m else "other"


def analyze_locale(en_data: dict, en_keys: list[str], locale_path: Path) -> dict:
    locale_data = load_arb(locale_path)
    locale_name = locale_path.stem.replace("app_", "")

    missing = []
    untranslated = []
    translated = []

    for key in en_keys:
        if key not in locale_data:
            missing.append(key)
        elif locale_data[key] == en_data[key]:
            untranslated.append(key)
        else:
            translated.append(key)

    return {
        "locale": locale_name,
        "file": locale_path.name,
        "total": len(en_keys),
        "translated": translated,
        "untranslated": untranslated,
        "missing": missing,
    }


def coverage_bar(pct: float, width: int = 20) -> str:
    filled = round(pct / 100 * width)
    return "█" * filled + "░" * (width - filled)


def group_by_prefix(keys: list[str]) -> dict[str, list[str]]:
    groups: defaultdict[str, list[str]] = defaultdict(list)
    for k in keys:
        groups[key_prefix(k)].append(k)
    return dict(sorted(groups.items(), key=lambda x: -len(x[1])))


def write_status_md(en_keys: list[str], results: list[dict]) -> None:
    lines = [
        "# Translation Status",
        "",
        "Auto-generated by `scripts/check_translation_coverage.py`.",
        "Do not edit manually.",
        "",
        f"**Template:** `{TEMPLATE}` — {len(en_keys)} keys",
        "",
        "## Summary",
        "",
        "| Locale | Translated | Missing | Untranslated | Coverage |",
        "|--------|-----------|---------|--------------|----------|",
    ]

    for r in results:
        total = r["total"]
        t = len(r["translated"])
        m = len(r["missing"])
        u = len(r["untranslated"])
        pct = t / total * 100 if total > 0 else 0
        lines.append(f"| {r['locale']} | {t} | {m} | {u} | {pct:.1f}% |")

    lines.append("")
    lines.append(
        "> **Untranslated** = key exists in locale file but value is identical "
        "to English (placeholder).  "
    )
    lines.append(
        "> **Missing** = key not in locale file at all (Flutter falls back to English)."
    )
    lines.append("")

    # Per-locale detail sections
    for r in results:
        locale = r["locale"]
        missing = r["missing"]
        untranslated = r["untranslated"]
        needs_work = missing + untranslated

        if not needs_work:
            lines.append(f"## {locale} — ✅ Complete")
            lines.append("")
            continue

        total = r["total"]
        t = len(r["translated"])
        pct = t / total * 100 if total > 0 else 0
        lines.append(f"## {locale} — {pct:.1f}% ({t}/{total})")
        lines.append("")

        if missing:
            grouped = group_by_prefix(missing)
            lines.append(f"### Missing keys ({len(missing)})")
            lines.append("")
            lines.append(
                "These keys are not in the locale file. "
                "Flutter falls back to English automatically."
            )
            lines.append("")
            for prefix, keys in grouped:
                lines.append(f"**{prefix}** ({len(keys)})")
                lines.append("")
                for k in keys:
                    lines.append(f"- `{k}`")
                lines.append("")
            # Fix: group_by_prefix returns dict, iterate .items()
            pass

        if untranslated:
            grouped = group_by_prefix(untranslated)
            lines.append(f"### Untranslated keys ({len(untranslated)})")
            lines.append("")
            lines.append(
                "These keys exist in the locale file but still have the English value."
            )
            lines.append("")
            # Show top 5 prefixes, collapse the rest
            shown = 0
            for prefix, keys in list(grouped.items())[:10]:
                lines.append(
                    f"<details><summary><b>{prefix}</b> ({len(keys)})</summary>"
                )
                lines.append("")
                for k in keys:
                    lines.append(f"- `{k}`")
                lines.append("")
                lines.append("</details>")
                lines.append("")
                shown += len(keys)

            remaining = len(untranslated) - shown
            if remaining > 0:
                lines.append(f"*...and {remaining} more across other prefixes.*")
                lines.append("")

    STATUS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    t0 = time.monotonic()

    # Load English template
    en_path = L10N_DIR / TEMPLATE
    if not en_path.exists():
        print(f"ERROR: Template not found: {en_path}", file=sys.stderr)
        sys.exit(1)

    en_data = load_arb(en_path)
    en_keys = get_translation_keys(en_data)

    # Find locale ARB files
    locale_files = sorted(p for p in L10N_DIR.glob("app_*.arb") if p.name != TEMPLATE)

    if not locale_files:
        print("No locale files found.")
        sys.exit(0)

    print(f"Template: {TEMPLATE} ({len(en_keys)} keys)")
    print(f"Locales: {len(locale_files)}")
    print()

    results = []
    for lf in locale_files:
        try:
            r = analyze_locale(en_data, en_keys, lf)
            results.append(r)
        except (json.JSONDecodeError, OSError) as e:
            print(f"  ERROR reading {lf.name}: {e}")

    # Print summary
    print(
        f"{'Locale':<8} {'Translated':>10} {'Missing':>8} {'Untranslated':>13} {'Coverage':>10}"
    )
    print("-" * 55)

    for r in results:
        total = r["total"]
        t = len(r["translated"])
        m = len(r["missing"])
        u = len(r["untranslated"])
        pct = t / total * 100 if total > 0 else 0
        bar = coverage_bar(pct)
        print(f"{r['locale']:<8} {t:>10} {m:>8} {u:>13} {pct:>7.1f}%  {bar}")

    print()

    # Per-locale missing key summary (top prefixes only)
    for r in results:
        needs_work = r["missing"] + r["untranslated"]
        if not needs_work:
            continue

        print(f"--- {r['locale']} needs work ({len(needs_work)} keys) ---")
        grouped = group_by_prefix(needs_work)
        for prefix, keys in list(grouped.items())[:8]:
            print(f"  {prefix}: {len(keys)}")
        remaining_groups = list(grouped.items())[8:]
        if remaining_groups:
            remaining_count = sum(len(ks) for _, ks in remaining_groups)
            print(
                f"  ... and {remaining_count} more in {len(remaining_groups)} other groups"
            )
        print()

    # Write TRANSLATION_STATUS.md
    # Fix the group_by_prefix iteration bug before writing
    write_status_md_fixed(en_keys, results)

    elapsed = time.monotonic() - t0
    print(f"Wrote {STATUS_FILE.relative_to(PROJECT)}")
    print(f"Completed in {elapsed:.2f}s")


def write_status_md_fixed(en_keys: list[str], results: list[dict]) -> None:
    lines = [
        "# Translation Status",
        "",
        "Auto-generated by `scripts/check_translation_coverage.py`. "
        "Do not edit manually.",
        "",
        f"**Template:** `{TEMPLATE}` — {len(en_keys)} keys",
        "",
        "## Summary",
        "",
        "| Locale | Translated | Missing | Untranslated | Coverage |",
        "|--------|-----------|---------|--------------|----------|",
    ]

    for r in results:
        total = r["total"]
        t = len(r["translated"])
        m = len(r["missing"])
        u = len(r["untranslated"])
        pct = t / total * 100 if total > 0 else 0
        lines.append(f"| {r['locale']} | {t} | {m} | {u} | {pct:.1f}% |")

    lines.append("")
    lines.append(
        "> **Untranslated** = key exists in locale file but value is identical "
        "to English (placeholder)."
    )
    lines.append(
        "> **Missing** = key not in locale file at all "
        "(Flutter falls back to English automatically)."
    )
    lines.append("")

    for r in results:
        locale = r["locale"]
        missing = r["missing"]
        untranslated = r["untranslated"]

        total = r["total"]
        t = len(r["translated"])
        pct = t / total * 100 if total > 0 else 0

        if not missing and not untranslated:
            lines.append(f"## {locale} — ✅ Complete")
            lines.append("")
            continue

        lines.append(f"## {locale} — {pct:.1f}% ({t}/{total})")
        lines.append("")

        if missing:
            grouped = group_by_prefix(missing)
            lines.append(f"### Missing keys ({len(missing)})")
            lines.append("")
            lines.append(
                "These keys are not in the locale file. "
                "Flutter uses the English value as fallback."
            )
            lines.append("")
            for prefix, keys in grouped.items():
                lines.append(
                    f"<details><summary><b>{prefix}</b> ({len(keys)})</summary>"
                )
                lines.append("")
                for k in keys:
                    lines.append(f"- `{k}`")
                lines.append("")
                lines.append("</details>")
                lines.append("")

        if untranslated:
            grouped = group_by_prefix(untranslated)
            lines.append(f"### Untranslated keys ({len(untranslated)})")
            lines.append("")
            lines.append(
                "These keys exist in the locale file but still have the "
                "English value. Either translate them or remove them from "
                "the locale file (Flutter will fall back to English)."
            )
            lines.append("")
            items = list(grouped.items())
            for prefix, keys in items[:15]:
                lines.append(
                    f"<details><summary><b>{prefix}</b> ({len(keys)})</summary>"
                )
                lines.append("")
                for k in keys:
                    lines.append(f"- `{k}`")
                lines.append("")
                lines.append("</details>")
                lines.append("")

            remaining = items[15:]
            if remaining:
                remaining_count = sum(len(ks) for _, ks in remaining)
                lines.append(
                    f"*...and {remaining_count} more keys across "
                    f"{len(remaining)} other prefixes.*"
                )
                lines.append("")

    STATUS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
