// SPDX-License-Identifier: GPL-3.0-or-later

/// Centralized node display name resolution.
///
/// Follows the official Meshtastic companion app naming conventions:
///
/// - Nodes without a user-configured name display as "Meshtastic XXXX"
///   where XXXX is the last 4 hex digits of the node number.
/// - The short name for such nodes is "XXXX" (last 4 hex digits).
/// - "Meshtastic XXXX" is a VALID display name (the firmware default),
///   and is never filtered out.
///
/// Only truly invalid placeholders are filtered:
/// - BLE advertising names: "Meshtastic_XXXX" (underscore variant)
/// - Raw hex ID placeholders: "!AABBCCDD"
/// - Decimal fallback strings: "Node 12345678" (Socialmesh legacy bug)
class NodeDisplayNameResolver {
  /// Matches BLE advertising name: "Meshtastic_XXXX" (underscore variant).
  /// This is the BLE peripheral name, not the user-facing node name.
  static final RegExp _bleDefaultPattern = RegExp(
    r'^Meshtastic_[0-9a-fA-F]{4}$',
  );

  /// Matches hex ID placeholders baked in by position-update placeholder
  /// code: "!AABBCCDD" or "!aabbccdd" (1-8 hex chars).
  static final RegExp _hexIdPattern = RegExp(r'^![0-9a-fA-F]{1,8}$');

  /// Matches legacy decimal fallback names: "Node 12345678".
  /// These were generated by Socialmesh code and are not valid names.
  static final RegExp _decimalFallbackPattern = RegExp(r'^Node \d+$');

  /// Returns the last 4 hex digits of a node number, uppercased.
  ///
  /// This matches the official Meshtastic firmware convention for
  /// deriving default short names from node numbers.
  static String shortHex(int nodeNum) {
    return nodeNum
        .toRadixString(16)
        .toUpperCase()
        .padLeft(4, '0')
        .substring(
          nodeNum.toRadixString(16).length > 4
              ? nodeNum.toRadixString(16).length - 4
              : 0,
        );
  }

  /// Returns the default display name for a node with no user-configured
  /// name, matching the official Meshtastic app: "Meshtastic XXXX".
  static String defaultName(int nodeNum) {
    return 'Meshtastic ${shortHex(nodeNum)}';
  }

  /// Returns the default short name for a node: last 4 hex digits.
  static String defaultShortName(int nodeNum) {
    return shortHex(nodeNum);
  }

  /// Resolves the best display name for a node.
  ///
  /// Resolution order:
  /// 1. longName (if genuine)
  /// 2. shortName (if genuine)
  /// 3. bleName (if genuine, e.g. third-party BLE names)
  /// 4. fallback or "Meshtastic XXXX" default
  static String resolve({
    required int nodeNum,
    String? longName,
    String? shortName,
    String? bleName,
    String? fallback,
  }) {
    final longResolved = sanitizeName(longName);
    if (longResolved != null) return longResolved;

    final shortResolved = sanitizeName(shortName);
    if (shortResolved != null) return shortResolved;

    final bleResolved = _normalizeBle(bleName);
    if (bleResolved != null) return bleResolved;

    return fallback ?? defaultName(nodeNum);
  }

  static bool isBleDefaultName(String? value) {
    final normalized = _normalize(value);
    if (normalized == null) return false;
    return _bleDefaultPattern.hasMatch(normalized);
  }

  /// Returns the name if it is a genuine user-configured or
  /// firmware-assigned name, or null if it is a placeholder that
  /// should not be displayed.
  ///
  /// "Meshtastic XXXX" (space variant) is considered a valid name
  /// per the official Meshtastic firmware convention and is NOT
  /// filtered out.
  static String? sanitizeName(String? value) {
    final normalized = _normalize(value);
    if (normalized == null) return null;
    if (_isPlaceholderName(normalized)) return null;
    return normalized;
  }

  /// Checks whether a name is an auto-generated placeholder that
  /// should be filtered out of display and caching.
  ///
  /// Note: "Meshtastic XXXX" (space variant) is NOT a placeholder.
  /// It is the firmware default long name and is a valid display name.
  static bool _isPlaceholderName(String value) {
    // BLE advertising default: "Meshtastic_XXXX" (underscore)
    if (_bleDefaultPattern.hasMatch(value)) return true;
    // Hex ID placeholder: "!aabbccdd"
    if (_hexIdPattern.hasMatch(value)) return true;
    // Legacy decimal fallback: "Node 12345678"
    if (_decimalFallbackPattern.hasMatch(value)) return true;
    return false;
  }

  static String? _normalize(String? value) {
    if (value == null) return null;
    final trimmed = value.trim();
    return trimmed.isEmpty ? null : trimmed;
  }

  static String? _normalizeBle(String? value) {
    final normalized = _normalize(value);
    if (normalized == null) return null;
    if (_isPlaceholderName(normalized)) return null;
    return normalized;
  }
}
